### ISSUE TITLE
GoCardless::$environment = 'sandbox'; must be set before account details

### ISSUE THREAD

**Issue by tomblomfield-zz** [gocardless/gocardless-legacy-php#12]
Otherwise, the environment is not set properly on the client.

Can we make this more flexible, please?

**Comment by DHS** [comment]
How about setting it to 'sandbox' if it's not declared by the time set_account_details is called?

**Comment by timrogers** [comment]
Issue resolved in v.0.4.0 - 9a16524a20f7173b69237c88651e8aba5d0b8112
