### ISSUE TITLE
Exceptions are not exposing API errors

### ISSUE THREAD

**Issue by tomblomfield-zz** [gocardless/gocardless-legacy-php#13]
``` php
try {
  $thing = GoCardless_PreAuthorization::find('BADRESOURCEID');
} catch (GoCardless_ApiException $e) {
  echo $e->getMessage();
  exit();
}
```

Returns this:

``` php
Array
(
  [error] => Array
  (
    [0] => Array
    (
    )
  )
)
```

Instead, we should be exposing a "resource not found" or similar

**Comment by timrogers** [comment]
For some exceptions, the error message is included, but the `getMessage()` method when called upon the exception just returns a textual representation of the JSON, e.g:

```
string(243) "Array
(
[errors] => Array
(
[pre_authorization] => Array
(
[0] => maximum amount exceeded for this period (GBP30.0 requested, only 
GBP10.0 remaining.)
)

)

)
```

Ideally, we'd display the message itself by pulling it out somehow. That's pretty hard though.

**Comment by timrogers** [comment]
Issue resolved in v.0.4.0 - 9a16524a20f7173b69237c88651e8aba5d0b8112

**Comment by zang** [comment]
Still got the text string. e.g. 

string(184) "Array
(
    [errors] => Array
        (
            [amount] => Array
                (
                    [0] => must be greater than or equal to 1.0
                )

```
    )
```

)
"
How can we parse that? 

thanks

**Comment by jacobpgn** [comment]
Hi @zang - you might want to use the getJson() or getError() functions on the Exception: https://github.com/gocardless/gocardless-php/blob/master/lib/GoCardless/Exceptions.php#L71

If you're working on a new integration then we'd recommend using our new API and new PHP library - they're much nicer! Check https://developer.gocardless.com/pro and https://github.com/gocardless/gocardless-pro-php
