### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by tanc** [gocardless/gocardless-legacy-php#15]
Just wondering what this code is licensed under?

**Comment by timrogers** [comment]
Hi - the license for the project is available at https://github.com/gocardless/gocardless-php/blob/master/LICENSE.

**Comment by tanc** [comment]
Great, thanks, I missed that. Just double checking but that's an MIT license isn't it? Got to make sure it passes the stringent license tests as I'm hoping to include it in a Drupal module.

**Comment by timrogers** [comment]
It does appear to be to me! Good luck with your module - drop us an email at help@gocardless.com if you need any help, or if you want to show it to us!

**Comment by tanc** [comment]
Thanks Tim, much appreciated!
