### ISSUE TITLE
PSR0 compatible for auto-loading

### ISSUE THREAD

**Issue by davedevelopment** [gocardless/gocardless-legacy-php#3]
Could we uppercase the gocardless directory and the files below it to make the classes compatible with [PSR0](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md)?

**Comment by DHS** [comment]
Hi Dave! Thanks for the suggestion. We've actually implemented this on the develop branch which just needs a little more testing before we release it.

**Comment by davedevelopment** [comment]
My bad, need to open my frickin eyes! Cheers

**Comment by DHS** [comment]
No worries!
