### ISSUE TITLE
Call to a member function confirm_resource() on a non-object when using via Composer

### ISSUE THREAD

**Issue by marcelgoya** [gocardless/gocardless-legacy-php#42]
Getting the following error when I'm executing your demo code 

require_once '../vendor/autoload.php';

$confirm_params = array(
              'resource_id'    => $_GET['resource_id'],
              'resource_type'  => $_GET['resource_type'],
              'resource_uri'   => $_GET['resource_uri'],
              'signature'      => $_GET['signature']
            );
            $confirmed_resource = \GoCardless::confirm_resource($confirm_params);

Fatal error: Call to a member function confirm_resource() on a non-object in /vendor/gocardless/gocardless/lib/GoCardless.php on line 139

**Comment by jacobpgn** [comment]
Hi marcelscheuch. It sounds like you haven't configured the client on that confirmation page - take a look at https://developer.gocardless.com/php/#initialization to see how this works and email help@gocardless.com if you're still having trouble!
